### PR TITLE
First try at modifying the Basics file

### PR DESCRIPTION
**Pull request by ssalaman**

### CODE REVIEW

**Comment by davidvogan** [comment]
Hi,

Thank you for starting, Susana!

I think that the text should have some basic formatting that indicates what
we're talking about, like setting the name of software in a typewriter
font. I'm less certain about variables: in discussions of actual math, we
could use mathjax to set things in TeX, but for software variables probably
typewriter font is right?? The examples Susana did of bits of atlas
interaction seem just right; what I'm asking about here is references from
the text. I did something crude and ridiculous to set 'atlas'; that ought
to be fixed, and extended appropriately to variable and data type names.

Talk to you tomorrow!

David

**Comment by ssalaman** [comment]
Hi, I see you (Dsvid)  were able to push the file. One interesting thing: when I click on view source to see what you did with the word `atlas' the page is the original blank page !

Why is that?

**Comment by ssalaman** [comment]
I did that on the url page.

**Comment by davidvogan** [comment]
I think that the "view source" think tries to show you the html code
or something; don't know why it's blank. But to see what I did, just
update the master branch and look at basics.rst.

**Pull request merged**
